package types

type MessageType int

const (
	UserMessage MessageType = iota
	AIMessage
	CommandMessage
	CommandResultMessage
	CommandErrorResultMessage
	InitMessage
	DirectoryMessage
	ImageMessage
	InstructionMessage
	SourceCodeMessage
	ShellCmdMessage
	ShellCmdResultMessage
)

type Message struct {
	Type    MessageType
	Content string // For text content, or file path for images (for prompt)
	Data    []byte // For raw image data

	Metadata map[string]any
}

type StreamChunk struct {
	Content          string
	ReasoningContent string
}

func (t MessageType) String() string {
	switch t {
	case UserMessage:
		return "User"
	case AIMessage:
		return "AI"
	case CommandMessage:
		return "Command"
	case CommandResultMessage:
		return "Command Result"
	case CommandErrorResultMessage:
		return "Command Error"
	case InitMessage:
		return "System"
	case DirectoryMessage:
		return "Directory"
	case ImageMessage:
		return "Image"
	case InstructionMessage:
		return "Instruction"
	case SourceCodeMessage:
		return "Source Code"
	case ShellCmdMessage:
		return "Shell Command"
	case ShellCmdResultMessage:
		return "Shell Command Result"
	default:
		return "Unknown"
	}
}

// IsEditable returns true if the message content can be edited by the user.
func (t MessageType) IsEditable() bool {
	switch t {
	case UserMessage:
		return true
	default:
		return false
	}
}

// IsSelectable returns true if the message can be focused/selected in Visual Mode.
func (t MessageType) IsSelectable() bool {
	switch t {
	case InitMessage, DirectoryMessage, InstructionMessage, SourceCodeMessage:
		return false
	default:
		return true
	}
}

// IsHistory returns true if the message should be saved to the session history file.
func (t MessageType) IsHistory() bool {
	switch t {
	case UserMessage, AIMessage, CommandMessage, CommandResultMessage, CommandErrorResultMessage, ImageMessage,
		InstructionMessage, SourceCodeMessage, ShellCmdMessage, ShellCmdResultMessage:
		return true
	default:
		return false
	}
}

// IsRegeneratable returns true if the message can serve as a starting point for regeneration.
func (t MessageType) IsRegeneratable() bool {
	switch t {
	case UserMessage, ImageMessage, ShellCmdMessage, ShellCmdResultMessage:
		return true
	default:
		return false
	}
}

// IsAI returns true if the message was generated by the AI.
func (t MessageType) IsAI() bool {
	switch t {
	case AIMessage:
		return true
	default:
		return false
	}
}
