name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Build binaries
        run: |
          mkdir release
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o release/coder-linux-amd64 ./cmd/coder
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o release/coder-darwin-amd64 ./cmd/coder
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o release/coder-darwin-arm64 ./cmd/coder
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o release/coder-windows-amd64.exe ./cmd/coder

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/coder-linux-amd64
            release/coder-darwin-amd64
            release/coder-darwin-arm64
            release/coder-windows-amd64.exe
