name: Web UI CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web/**'
      - '.github/workflows/web-ui.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web/**'
      - '.github/workflows/web-ui.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./web

    - name: Lint code
      run: npm run lint
      working-directory: ./web

    - name: Build project
      run: npm run build
      working-directory: ./web
